import 'dotenv/config';
import Groq from "groq-sdk";

// Initialize the Groq client.
// By default, the SDK automatically looks for the process.env.GROQ_API_KEY environment variable.
const groq = new Groq();

/**
 * Sends the git diff to Groq (Llama 3.3 70B) for architectural validation.
 * @param diff The raw git diff string extracted by the interceptor.
 * @returns The AI's judgement as a string.
 */

export async function analyzeDiff(diff: string, projectRules: string): Promise<string> {
    //The master prompt to ensure the AI is gonna judge the base code correctly by using aegis.config.json
    const systemPrompt = `You are a ruthless, elite Tech Lead and Staff Engineer. 
    Your job is to analyze the following git diff and enforce the company's architectural rules.
    Here is the configuration containing the company's strict rules:
    <rules>
    ${projectRules}
    </rules>

    1. If the git diff violates ANY of the rules specified, you MUST output "REJECTED" followed by a
  harsh reprimand explaining exactly which rule was broken.
    2. If the code is clean and perfectly follows the rules, output "APPROVED" followed by a short
  compliment.
    Do NOT output the git diff itself. Only output your judgement.`;

    try {
        const response = await groq.chat.completions.create({
            model: "qwen/qwen3.6-27b", // Fixed model ID based on the 2026 dashboard
            messages: [
                { role: "system", content: systemPrompt },
                { role: "user", content: `Analyze this git diff:\n\n${diff}` }
            ],
            temperature: 0.1, // Low temperature to maximize logical consistency and determinism
            max_tokens: 4096, // Hard limit increased to allow the AI to finish its <think> block
        });

        // Extract the response text or provide a fallback string
        return response.choices[0]?.message?.content || "No response generated by the AI.";
        
    } catch (err: unknown) {
        // Safety fallback in case the API is down or the key is missing
        if (err instanceof Error) {
            throw new Error(`Error communicating with Groq API: ${err.message}`);
        }
        throw new Error('Unknown error occurred while communicating with Groq API.');
    }
}
